### ISSUE TITLE
Input String was not in a correct format

### ISSUE THREAD

**Issue by hurtsky** [Tokeiburu/RagnarokSDE#2]
i have no problem with last stable version,

but with your latest version i get this error

here the exception
```
--------------          Message          --------------
Input string was not in a correct format.
--------------        Stack trace        --------------
   at GrfToWpfBridge.Application.DefaultErrorHandler._reportAnyManagedExceptions(String message, Exception exception, ErrorLevel errorLevel)
   at GrfToWpfBridge.Application.DefaultErrorHandler.Handle(Exception exception, ErrorLevel errorLevel)
   at SDE.View.SdeEditor._reloadDatabase(Boolean alreadyAsync)
   at SDE.View.SdeEditor.<ReloadDatabase>b__2()
   at GRF.Threading.GrfThread.<>c__DisplayClass4.<Start>b__3()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

--------------         Exception         --------------
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at SDE.Editor.Generic.Parsers.DbIOClientCheevo._loadEntry(Table`2 table, LuaKeyValue item)
   at SDE.Editor.Generic.Parsers.DbIOClientCheevo.Loader(AbstractDb`1 db, String file)
   at SDE.Editor.Generic.Parsers.DbIOClientCheevo.Loader(DbDebugItem`1 debug, AbstractDb`1 db)
   at SDE.Editor.Generic.Core.DbClientCheevo._loadDb()
   at SDE.Editor.Generic.Core.AbstractDb`1.LoadDb()
   at SDE.Editor.Engines.DatabaseEngine.SdeDatabase.Reload(IProgress progress)
   at SDE.View.SdeEditor._reloadDatabase(Boolean alreadyAsync)
```

thank you for updating this powerful editor

**Comment by Tokeiburu** [comment]
Most likely already fixed.
